### ISSUE TITLE
full api

### ISSUE THREAD

**Issue by gedw99** [caarlos0/go-gumroad#32]
Hey @caarlos0 

Do you know if there is a golang API for  https://app.gumroad.com/api ?

**Comment by dwisiswant0** [comment]
I was just about to ask the same thing a sec ago. Checking out the docs, it seems like they're asking for `product_id` instead of `product_permalink` to verify the license. Can you quickly confirm if this package is still on point, @caarlos0? Thanks!

**Comment by caarlos0** [comment]
I don't know of any full implementation, no...

this is one is mainly for my usecase, which includes only validating licenses for now...

**Comment by gedw99** [comment]
cheers @caarlos0 

Yeah I went hunted for a swagger / openapi file but lucked out :)

I will close this ...
